### ISSUE TITLE
PDM library drops microphone samples

### ISSUE THREAD

**Issue by jremington** [victorromeo/ArduinoPDM#2]
I'm using the Adafruit Clue as a recorder of audio clips, and discovered that audio samples are dropped every 2048 samples (as I have presently coded it). 

Please see code and complete description of the problem at https://forums.adafruit.com/viewtopic.php?t=205785

 I'm presently using Adafruit's modification of this library, and wanted to try the version posted here, but I run into these compile-time error messages, and don't yet know how to fix them:

In file included from C:\Users\Jim\Desktop\Clue\PDM_fileB2\src\PDM.cpp:24:

> C:\Users\Jim\AppData\Local\Arduino15\packages\adafruit\hardware\nrf52\1.5.0\cores\nRF5/nordic/nrfx/hal/nrf_pdm.h:521:57: note:   initializing argument 1 of 'void nrf_pdm_clock_set(NRF_PDM_Type*, nrf_pdm_freq_t)'
> 
>   521 | NRF_STATIC_INLINE void nrf_pdm_clock_set(NRF_PDM_Type * p_reg, nrf_pdm_freq_t pdm_freq)
> 
>       |                                          ~~~~~~~~~~~~~~~^~~~~
> 
> C:\Users\Jim\Desktop\Clue\PDM_fileB2\src\PDM.cpp:29:29: error: cannot convert 'nrf_pdm_freq_t' to 'NRF_PDM_Type*'

**Comment by jremington** [comment]
Audacity screen showing typical glitch at a buffer boundary, sample of recorded 440 Hz tone. The recording sounds terrible when played back!

 
![Capture](https://github.com/victorromeo/ArduinoPDM/assets/5509037/2dc311e9-d179-41be-8ab6-312ea67641b6)

**Comment by Montvydas** [comment]
This is pretty old now, but thought of letting you know @jremington that the issue you had with the library is the way how it tries to pass the data in the nrf_pdm_clock_set function, it's not passing parameter NRF_PDM for some reason... You need add the parameter into all instances of the function calls e.g.:

```nrf_pdm_clock_set(NRF_PDM_FREQ_1280K);``` ---> ```nrf_pdm_clock_set(NRF_PDM, NRF_PDM_FREQ_1280K);```

**Comment by jremington** [comment]
Thanks!  I found that merely increasing the PDM buffer size was enough to solve the problem.
